window.PORTFOLIO_CASE_STUDIES = [
  {
    slug: "brain-tumor-classification",
    year: "2025 · Thesis",
    title: "ResNet-based few-shot learning for brain tumor classification",
    summary: "A research case study on learning from limited MRI image examples.",
    problem: "Brain-tumor image classification becomes harder when labelled examples are limited and image conditions vary.",
    user: "Research audiences exploring more data-efficient medical-image classification methods.",
    solution: "Investigated a ResNet-based few-shot learning approach and evaluated how convolutional representations can support classification from a small number of examples.",
    keyFeatures: ["Few-shot learning experiment design", "ResNet-based image representation", "MRI image preparation and evaluation"],
    challenge: "Keeping the experimental process rigorous while working with limited examples and medically sensitive subject matter.",
    impact: "Produced a documented research contribution on few-shot learning for brain-tumor classification; results are communicated through the published work rather than product-performance claims.",
    techChoices: ["Python", "Deep learning", "ResNet", "Image processing"],
    screenshotNote: "Research figures and experiment artefacts will be selected for public display later."
  },
  {
    slug: "nutrisee",
    year: "2024 · Bangkit",
    title: "Nutrisee — image recognition for nutritional-fact analysis",
    summary: "A cross-functional project that turns nutrition-label images into more accessible information.",
    problem: "Nutrition facts can be difficult to inspect quickly from packaging, especially when people need to compare details at a glance.",
    user: "People who want a clearer way to inspect nutritional information from product labels.",
    solution: "Built an image-recognition workflow that analyses nutritional-fact imagery and supports a more direct interpretation of the label.",
    keyFeatures: ["Image-based nutrition-label analysis", "Cross-functional product collaboration", "Nutritional-fact interpretation workflow"],
    challenge: "Translating an ML capability into a useful product flow while coordinating across a seven-person team.",
    impact: "Created a working team project that connected machine-learning experimentation with a practical health-information use case.",
    techChoices: ["TensorFlow", "Python", "Image processing", "Mobile product collaboration"],
    screenshotNote: "Product screens will be added after the public-safe visual set is prepared."
  },
  {
    slug: "aspirasi",
    year: "2024 · Mobile",
    title: "ASPIRASI — a Firebase-backed digital guest book",
    summary: "A mobile guest-book concept designed around straightforward submission and retrieval.",
    problem: "Paper or fragmented guest-book processes make entries harder to collect, revisit, and manage consistently.",
    user: "Event or activity participants submitting an entry, and organisers who need to review it.",
    solution: "Developed a digital guest-book experience backed by Firebase so entries can be captured and accessed through one mobile workflow.",
    keyFeatures: ["Digital entry submission", "Firebase-backed data handling", "Mobile-first guest-book flow"],
    challenge: "Keeping the interaction simple while connecting the mobile interface to a reliable backend service.",
    impact: "Demonstrated a paperless alternative for collecting and retrieving guest-book entries in one place.",
    techChoices: ["Kotlin", "Firebase", "Android", "REST APIs"],
    screenshotNote: "Application screenshots will be curated later."
  },
  {
    slug: "asah",
    year: "2023 · Mobile",
    title: "ASAH — a health-focused super app",
    summary: "A six-person mobile-team project exploring a broader health application experience.",
    problem: "Health-related tasks can be scattered across separate tools and unclear user journeys.",
    user: "People looking for a more connected mobile experience around everyday health needs.",
    solution: "Contributed to a health-focused super-app concept with a six-person team, aligning individual mobile work with the shared product direction.",
    keyFeatures: ["Health-focused mobile flows", "Collaborative product development", "Native Android application foundation"],
    challenge: "Maintaining a coherent experience while several contributors build parts of the same mobile product.",
    impact: "Strengthened experience in collaborative Android delivery and turning a broad product idea into focused mobile flows.",
    techChoices: ["Kotlin", "Android", "Team collaboration"],
    screenshotNote: "Public screenshots will be added once the original assets are ready for release."
  },
  {
    slug: "ponorogo-city",
    year: "2023 · Web",
    title: "Ponorogo city landing page",
    summary: "A four-person web project focused on presenting a city through a clear landing-page experience.",
    problem: "A city-focused website needs to introduce key information without overwhelming visitors on their first visit.",
    user: "Visitors looking for a quick, approachable introduction to Ponorogo.",
    solution: "Built a landing page with a four-person team, using a focused page structure to present city-oriented information on the web.",
    keyFeatures: ["Responsive landing-page structure", "City-oriented content presentation", "Collaborative web delivery"],
    challenge: "Turning broad city information into an understandable first-screen experience and a coherent page hierarchy.",
    impact: "Delivered a collaborative web project that practised content hierarchy, frontend implementation, and shared development workflow.",
    techChoices: ["HTML", "CSS", "JavaScript", "PHP"],
    screenshotNote: "A selected responsive page capture will be added later."
  },
  {
    slug: "ml-desktop-experiments",
    year: "2022—2023 · Research",
    title: "Prediction and decision-making experiments across desktop and ML",
    summary: "A set of exploratory projects spanning prediction models, decision support, and desktop interfaces.",
    problem: "Small exploratory tools still need a clear bridge between model output and the person making a decision.",
    user: "Learners and evaluators working with prediction or decision-support experiments.",
    solution: "Built and explored several small applications that combined prediction-oriented modelling with accessible desktop interfaces.",
    keyFeatures: ["Prediction experiments", "Decision-support exploration", "Desktop interface prototypes"],
    challenge: "Making experimental models understandable enough to evaluate through a usable interface.",
    impact: "Established practical foundations in Python, desktop prototyping, and applied machine-learning experimentation.",
    techChoices: ["Python", "Tkinter", "Deep learning", "Data experimentation"],
    screenshotNote: "Screenshots will be chosen per experiment when the archive is consolidated."
  }
];
